#
# Copyright (C) YuqiaoZhang(HanetakaChou)
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

_hand_landmarker_create
_hand_landmarker_detect_image
_hand_landmarker_detect_for_video
_hand_landmarker_detect_async
_hand_landmarker_close_result
_hand_landmarker_close
_face_landmarker_create
_face_landmarker_detect_image
_face_landmarker_detect_for_video
_face_landmarker_detect_async
_face_landmarker_close_result
_face_landmarker_close
_pose_landmarker_create
_pose_landmarker_detect_image
_pose_landmarker_detect_for_video
_pose_landmarker_detect_async
_pose_landmarker_close_result
_pose_landmarker_close
